package main;

import .*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class form_login extends javax.swing.JFrame {

    int  xx, xy;
    /**
     * Creates new form form_login
     */
    public form_login() {
        initComponents();
    }
    
    void bersih(){
    t_username.setText("Ussername");
    t_pasword.setText("Password");      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t_username = new javax.swing.JTextField();
        t_pasword = new javax.swing.JTextField();
        buttonlogin = new javax.swing.JButton();
        icon_exit = new javax.swing.JLabel();
        icon_backround = new javax.swing.JLabel();
        icon_maskot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("Ussername");
        t_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 40));

        t_pasword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_pasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_pasword.setText("Password");
        t_pasword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        t_pasword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_paswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_paswordFocusLost(evt);
            }
        });
        t_pasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_paswordActionPerformed(evt);
            }
        });
        jPanel1.add(t_pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 40));

        buttonlogin.setBackground(new java.awt.Color(51, 51, 255));
        buttonlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonlogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogin.setText("LOGIN");
        buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 40));

        icon_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_exit.png"))); // NOI18N
        icon_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_exitMouseClicked(evt);
            }
        });
        jPanel1.add(icon_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        icon_backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_bacround.jpg"))); // NOI18N
        icon_backround.setText("jLabel5");
        jPanel1.add(icon_backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 250, 250));

        icon_maskot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_maskot.png"))); // NOI18N
        jPanel1.add(icon_maskot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
         this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_paswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_paswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_paswordActionPerformed

    private void buttonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonloginActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        // TODO add your handling code here:
        String ussername=t_username.getText();
        if(ussername.equals("Ussername")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_paswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_paswordFocusGained
        // TODO add your handling code here:
         String pass=t_pasword.getText();
        if(pass.equals("Password")){
            t_pasword.setText("");
        }
    }//GEN-LAST:event_t_paswordFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
       
        String ussername = t_username.getText();
        if(ussername.equals("")||ussername.equals("Ussername")){
            t_username.setText("Ussername");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_paswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_paswordFocusLost

         String pass = t_pasword.getText();
        if(pass.equals("")||pass.equals("Password")){
            t_pasword.setText("Password");
        }
    }//GEN-LAST:event_t_paswordFocusLost

    private void icon_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_exitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_icon_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonlogin;
    private javax.swing.JLabel icon_backround;
    private javax.swing.JLabel icon_exit;
    private javax.swing.JLabel icon_maskot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t_pasword;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
