/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public menu_utama() {
        initComponents();
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
       execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_konten = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_navbar.setBackground(new java.awt.Color(51, 204, 255));
        pn_navbar.setPreferredSize(new java.awt.Dimension(792, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_maskot.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PETSHOP (FETAMI)");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(0, 204, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 393));

        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_konten.setBackground(new java.awt.Color(255, 255, 255));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_kontenLayout = new javax.swing.GroupLayout(pn_konten);
        pn_konten.setLayout(pn_kontenLayout);
        pn_kontenLayout.setHorizontalGroup(
            pn_kontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        pn_kontenLayout.setVerticalGroup(
            pn_kontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        getContentPane().add(pn_konten, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1014, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    pn_utama.add(new content_bg());
    pn_utama.repaint();
    pn_utama.revalidate();

    }//GEN-LAST:event_formWindowOpened

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_konten;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        
        ImageIcon iconHome          = new ImageIcon (getClass().getResource("/img/icon_home.png"));
        ImageIcon iconMaster        = new ImageIcon (getClass().getResource("/img/icon_master.png"));
        ImageIcon iconbarang        = new ImageIcon (getClass().getResource("/img/icon_barang.png"));
        ImageIcon iconTransaksi     = new ImageIcon(getClass().getResource("/img/icon_transaksi.png"));
        ImageIcon iconLaporan       = new ImageIcon(getClass().getResource("/img/icon_laporan.png")); 
        ImageIcon iconJenisBarang   = new ImageIcon (getClass().getResource("/img/icon_jenisbarang.jpg"));
        ImageIcon iconSupliyer      = new ImageIcon (getClass().getResource("/img/icon_supliyer.png"));
        ImageIcon iconPengguna      = new ImageIcon(getClass().getResource("/img/icon_pengguna.png"));
        ImageIcon iconDataPelanggan = new ImageIcon(getClass().getResource("/img/icon_datapelanggan.jpg")); 
        ImageIcon iconPemesananBarang1   = new ImageIcon (getClass().getResource("/img/icon_pemesananbarangtransa.png"));
        ImageIcon iconBarangMasuk        = new ImageIcon (getClass().getResource("/img/icon_barangmasuk.png"));
        ImageIcon iconBarangkeluar       = new ImageIcon(getClass().getResource("/img/icon_barangkeluar.png"));
        ImageIcon iconStokBarang         = new ImageIcon(getClass().getResource("/img/icon_stokbarang.jpg")); 
        ImageIcon iconPemesananBarang2   = new ImageIcon(getClass().getResource("/img/icon_pemesananbaranglapor.png")); 
        
        menu_item masBarang1  = new menu_item (null, true, iconbarang,"Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
               pn_utama.removeAll();
               pn_utama.add(new Form_Barang());
               pn_utama.repaint();
               pn_utama.revalidate();

            }
        });
        
        
        menu_item masBarang2  = new menu_item (null, true, iconJenisBarang,"Jenis barang", null);
        menu_item masBarang3  = new menu_item (null, true, iconSupliyer,"Suplier", null);
        menu_item masBarang4  = new menu_item (null, true, iconPengguna,"Pengguna", null);
        menu_item masBarang5  = new menu_item (null, true, iconDataPelanggan,"Data pelanggan", null);
        
        menu_item transaksi1  = new menu_item (null, true, iconPemesananBarang1,"Pemesanan barang", null);
        menu_item transaksi2  = new menu_item (null, true, iconBarangMasuk,"Barang masuk", null);
        menu_item transaksi3  = new menu_item (null, true, iconBarangkeluar,"Barang keluar", null);
        
        menu_item laporan1  = new menu_item (null, true, iconStokBarang,"Stok barang", null);
        menu_item laporan2  = new menu_item (null, true, iconPemesananBarang2,"Pemesanan barang", null);
        
   
        menu_item menuHome          = new menu_item (iconHome, false,null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               pn_utama.removeAll();
               pn_utama.add(new content_bg());
               pn_utama.repaint();
               pn_utama.revalidate();
            }
        });
        menu_item menuMaster        = new menu_item (iconMaster, false,null, "master", null,masBarang1,masBarang2,masBarang3,masBarang4,masBarang5);
        menu_item menuTransaksi     = new menu_item (iconTransaksi, false,null, "Transaksi", null,transaksi1,transaksi2,transaksi3);
        menu_item menuLaporan       = new menu_item (iconLaporan, false,null, "Laporan", null,laporan1,laporan2);
        
        
        addMenu(menuHome,menuMaster,menuTransaksi,menuLaporan);  
       
    }
    private void addMenu (menu_item... menu){
        for (int i = 0; i <menu.length; i++){
            pn_menu.add(menu[i]);
            ArrayList<menu_item>subMenu = menu[i].getSubMenu();
            for (menu_item m : subMenu){
                addMenu (m);
                
}
        }
            pn_menu.revalidate();
            
    }
}
